
import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageData = (id: string) => {
  const imageData = PlaceHolderImages.find(img => img.id === id);
  return {
    imageUrl: imageData?.imageUrl || 'https://picsum.photos/seed/error/600/600',
    imageHint: imageData?.imageHint || 'placeholder image'
  };
};

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Wireless Headphones',
    description: 'High-fidelity sound and noise cancellation.',
    longDescription: 'Experience immersive sound with these state-of-the-art wireless headphones. Featuring active noise cancellation, a 20-hour battery life, and a comfortable over-ear design. Perfect for music lovers and frequent travelers.',
    price: 199.99,
    ...getImageData('prod_001'),
    category: 'Electronics',
    stock: 25,
  },
  {
    id: 'prod_002',
    name: 'Cotton T-Shirt',
    description: 'Soft, breathable, and sustainably sourced.',
    longDescription: 'A wardrobe essential, this t-shirt is made from 100% organic cotton for a soft and comfortable feel. Its classic cut and durable construction make it perfect for everyday wear. Available in various colors.',
    price: 24.99,
    ...getImageData('prod_002'),
    category: 'Apparel',
    stock: 150,
  },
  {
    id: 'prod_003',
    name: 'Ceramic Mug Set',
    description: 'Set of 4 handcrafted minimalist mugs.',
    longDescription: 'Start your day right with this beautiful set of four ceramic mugs. Each mug is handcrafted and features a unique, minimalist design. They are microwave and dishwasher safe, combining style with practicality.',
    price: 49.99,
    ...getImageData('prod_003'),
    category: 'Home Goods',
    stock: 50,
  },
  {
    id: 'prod_004',
    name: 'Classic Hardcover Novel',
    description: 'A timeless story of adventure and discovery.',
    longDescription: 'Rediscover a literary classic with this beautifully bound hardcover edition. This novel has captivated readers for generations with its compelling characters and timeless themes. A must-have for any bookshelf.',
    price: 18.50,
    ...getImageData('prod_004'),
    category: 'Books',
    stock: 80,
  },
  {
    id: 'prod_005',
    name: 'Professional Laptop',
    description: 'Powerful, sleek, and ready for any task.',
    longDescription: 'Boost your productivity with this high-performance laptop. Equipped with the latest processor, a stunning display, and a lightweight design, it\'s built for professionals on the go. Features all-day battery life.',
    price: 1299.00,
    ...getImageData('prod_005'),
    category: 'Electronics',
    stock: 15,
  },
  {
    id: 'prod_006',
    name: 'Denim Jeans',
    description: 'Classic straight-fit for timeless style.',
    longDescription: 'Crafted from premium denim, these jeans offer both comfort and durability. The classic straight-fit design is versatile and never goes out of style. Perfect for casual outings or dressing up for a night out.',
    price: 89.99,
    ...getImageData('prod_006'),
    category: 'Apparel',
    stock: 120,
  },
  {
    id: 'prod_007',
    name: 'Scented Candle',
    description: 'Lavender and chamomile for relaxation.',
    longDescription: 'Create a tranquil atmosphere with this scented candle. Made from natural soy wax and infused with lavender and chamomile essential oils, it helps to calm the mind and promote relaxation. Burns for up to 50 hours.',
    price: 22.00,
    ...getImageData('prod_007'),
    category: 'Home Goods',
    stock: 200,
  },
  {
    id: 'prod_008',
    name: 'Non-Fiction Essays',
    description: 'A thought-provoking collection on modern life.',
    longDescription: 'Explore a wide range of topics in this insightful collection of essays. Written by a leading contemporary thinker, this book challenges perspectives on technology, culture, and society. A stimulating read for the curious mind.',
    price: 16.95,
    ...getImageData('prod_008'),
    category: 'Books',
    stock: 65,
  },
  {
    id: 'prod_009',
    name: 'Gaming Mouse',
    description: 'High-precision sensor and customizable RGB.',
    longDescription: 'Gain a competitive edge with this high-precision gaming mouse. It features an ultra-accurate optical sensor, programmable buttons, and customizable RGB lighting to match your setup. Ergonomically designed for long gaming sessions.',
    price: 65.00,
    ...getImageData('prod_009'),
    category: 'Electronics',
    stock: 40,
  },
  {
    id: 'prod_010',
    name: 'Wool Scarf',
    description: 'Stay warm with this 100% merino wool scarf.',
    longDescription: 'Wrap yourself in luxury with this incredibly soft and warm scarf. Made from 100% pure merino wool, it provides excellent insulation against the cold while being lightweight and breathable. A stylish and practical winter accessory.',
    price: 55.00,
    ...getImageData('prod_010'),
    category: 'Apparel',
    stock: 90,
  },
  {
    id: 'prod_011',
    name: 'Modern Wall Clock',
    description: 'Silent, non-ticking, minimalist design.',
    longDescription: 'This modern wall clock is a functional piece of art. Its minimalist design and silent, non-ticking mechanism make it a perfect addition to any room, from the office to the living room. Easy to hang and powered by a single AA battery.',
    price: 45.00,
    ...getImageData('prod_011'),
    category: 'Home Goods',
    stock: 75,
  },
  {
    id: 'prod_012',
    name: 'Sci-Fi Saga',
    description: 'The complete best-selling space opera.',
    longDescription: 'Embark on an epic journey across the galaxy with this complete collection of a best-selling sci-fi saga. This box set includes all the books in the series, known for its intricate world-building and memorable characters.',
    price: 75.00,
    ...getImageData('prod_012'),
    category: 'Books',
    stock: 30,
  },
  {
    id: 'prod_013',
    name: 'Smartwatch',
    description: 'Track fitness, notifications, and more.',
    longDescription: 'Stay connected and active with this versatile smartwatch. Track your workouts, monitor your heart rate, receive notifications, and make payments, all from your wrist. Features a long-lasting battery and a water-resistant design.',
    price: 249.99,
    ...getImageData('prod_013'),
    category: 'Electronics',
    stock: 30,
  },
  {
    id: 'prod_014',
    name: 'Bluetooth Speaker',
    description: 'Portable, waterproof, with rich bass.',
    longDescription: 'Take your music anywhere with this portable Bluetooth speaker. Its rugged, waterproof design makes it perfect for outdoor adventures. Enjoy rich sound with deep bass for up to 12 hours on a single charge.',
    price: 79.99,
    ...getImageData('prod_014'),
    category: 'Electronics',
    stock: 60,
  },
  {
    id: 'prod_015',
    name: 'Leather Jacket',
    description: 'Classic biker style, premium leather.',
    longDescription: 'Add an edge to your wardrobe with this timeless leather biker jacket. Made from premium, full-grain leather, it features classic hardware and a comfortable fit. A statement piece that gets better with age.',
    price: 349.00,
    ...getImageData('prod_015'),
    category: 'Apparel',
    stock: 25,
  },
  {
    id: 'prod_016',
    name: 'Running Sneakers',
    description: 'Lightweight and responsive for daily runs.',
    longDescription: 'Hit your stride with these lightweight running sneakers. Engineered for comfort and performance, they feature responsive cushioning and a breathable upper. Ideal for daily training and race day.',
    price: 129.99,
    ...getImageData('prod_016'),
    category: 'Apparel',
    stock: 100,
  },
  {
    id: 'prod_017',
    name: 'Adjustable Desk Lamp',
    description: 'Modern LED lamp with dimmable light.',
    longDescription: 'Illuminate your workspace with this sleek, adjustable LED desk lamp. It offers multiple brightness levels and color temperatures to suit your needs. Its flexible design allows you to direct light exactly where you need it.',
    price: 59.99,
    ...getImageData('prod_017'),
    category: 'Home Goods',
    stock: 40,
  },
  {
    id: 'prod_018',
    name: 'Cozy Throw Blanket',
    description: 'Soft fleece for ultimate comfort.',
    longDescription: 'Snuggle up with this ultra-soft fleece throw blanket. Perfect for a cozy night in, it\'s lightweight yet incredibly warm. A stylish addition to your living room or bedroom decor.',
    price: 39.99,
    ...getImageData('prod_018'),
    category: 'Home Goods',
    stock: 110,
  },
  {
    id: 'prod_019',
    name: 'The World on a Plate',
    description: 'A journey through international cuisine.',
    longDescription: 'Expand your culinary horizons with this comprehensive cookbook. "The World on a Plate" features authentic recipes from around the globe, complete with beautiful photography and step-by-step instructions.',
    price: 34.99,
    ...getImageData('prod_019'),
    category: 'Books',
    stock: 55,
  },
  {
    id: 'prod_020',
    name: 'Mystery Thriller Novel',
    description: 'A gripping tale of suspense and intrigue.',
    longDescription: 'From a best-selling author comes a mystery that will keep you on the edge of your seat. Full of twists and turns, this thriller is a compulsive read you won\'t be able to put down.',
    price: 15.99,
    ...getImageData('prod_020'),
    category: 'Books',
    stock: 95,
  },
  {
    id: 'prod_021',
    name: '4K UHD Monitor',
    description: 'Stunning visuals with vibrant colors.',
    longDescription: 'Upgrade your viewing experience with this 27-inch 4K UHD monitor. It delivers breathtakingly sharp images and vibrant colors, making it ideal for creative professionals and gamers alike. Features a slim bezel design and multiple connectivity options.',
    price: 449.99,
    ...getImageData('prod_021'),
    category: 'Electronics',
    stock: 22,
  },
  {
    id: 'prod_022',
    name: 'Mechanical Keyboard',
    description: 'Tactile switches for a satisfying typing feel.',
    longDescription: 'Experience a superior typing and gaming experience with this mechanical keyboard. Featuring tactile switches, full RGB backlighting, and a durable aluminum frame. It\'s built to last and perform.',
    price: 119.99,
    ...getImageData('prod_022'),
    category: 'Electronics',
    stock: 38,
  },
  {
    id: 'prod_023',
    name: 'Stylish Sunglasses',
    description: 'UV protection with a modern flair.',
    longDescription: 'Protect your eyes in style with these modern sunglasses. Offering 100% UV protection, they feature lightweight frames and polarized lenses to reduce glare. A perfect accessory for any sunny day.',
    price: 75.00,
    ...getImageData('prod_023'),
    category: 'Apparel',
    stock: 88,
  },
  {
    id: 'prod_024',
    name: 'Comfortable Hoodie',
    description: 'Fleece-lined for extra warmth and softness.',
    longDescription: 'The perfect hoodie for warmth and comfort. Lined with soft fleece, it features a classic design with a drawstring hood and a spacious front pocket. Ideal for cool evenings and relaxed weekends.',
    price: 65.00,
    ...getImageData('prod_024'),
    category: 'Apparel',
    stock: 110,
  },
  {
    id: 'prod_025',
    name: 'Plush Bath Towel Set',
    description: 'Absorbent, soft, and luxurious cotton.',
    longDescription: 'Wrap yourself in luxury with this 6-piece bath towel set. Made from 100% long-staple cotton, these towels are exceptionally soft, absorbent, and durable. The set includes two bath towels, two hand towels, and two washcloths.',
    price: 54.99,
    ...getImageData('prod_025'),
    category: 'Home Goods',
    stock: 95,
  },
  {
    id: 'prod_026',
    name: 'Aesthetic Desk Organizer',
    description: 'Keep your workspace tidy and stylish.',
    longDescription: 'Bring order and style to your desk with this minimalist organizer. Made from natural wood and metal, it provides compartments for pens, notebooks, and other small essentials, helping you stay focused and productive.',
    price: 28.00,
    ...getImageData('prod_026'),
    category: 'Home Goods',
    stock: 130,
  },
  {
    id: 'prod_027',
    name: 'Cookbook for Beginners',
    description: 'Easy and delicious recipes for new cooks.',
    longDescription: 'Unleash your inner chef with this cookbook designed for beginners. It features over 100 easy-to-follow recipes with clear instructions and helpful tips, making cooking a fun and rewarding experience.',
    price: 21.99,
    ...getImageData('prod_027'),
    category: 'Books',
    stock: 70,
  },
  {
    id: 'prod_028',
    name: 'The Art of Mindfulness',
    description: 'A practical guide to living in the present.',
    longDescription: 'Discover peace and clarity with "The Art of Mindfulness." This guide offers practical exercises and insights to help you reduce stress, improve focus, and cultivate a greater sense of well-being in your daily life.',
    price: 17.50,
    ...getImageData('prod_028'),
    category: 'Books',
    stock: 85,
  },
];

    